 
[[mounts]]
  source = "node_modules/@hyas/core/assets"
  target = "assets"

[[mounts]]
  source = "node_modules/@hyas/core/layouts"
  target = "layouts"

[[mounts]]
  source = "node_modules/gethyas/assets"
  target = "assets"

[[mounts]]
  source = "node_modules/gethyas/static"
  target = "static"

[[mounts]]
  source = "assets"
  target = "assets"

[[mounts]]
  source = "layouts"
  target = "layouts"

[[mounts]]
  source = "static"
  target = "static"

[[mounts]]
  source = "node_modules/bootstrap/scss"
  target = "assets/scss/bootstrap"

[[mounts]]
  source = "node_modules/@hyas/bootstrap/layouts"
  target = "layouts"
